[tool.poetry]
name = "saude"
version = "0.1.0"
description = ""
authors = ["matheusgb <matheusgbr98@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
