# Generated by Django 5.1.3 on 2024-11-07 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalentity',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Somente números são permitidos.')]),
        ),
        migrations.AlterField(
            model_name='professionalentity',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalentity',
            name='social_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
